language: python

python:
  - "3.5"

install:
  - pip install pyvodb
  - pip install pytest

script:
  # This loads the DB, making sure it *can* be loaded
  - |
      python -c '
      from pyvodb.load import get_db
      from pyvodb.tables import Event
      db=get_db(".")
      cnt=db.query(Event).count()
      print(cnt)
      if not cnt:
          exit("no events found")'

sudo: false
