city: praha
start: 2013-06-19
name: Pražské PyVo
number: 27
topic: security
venue: na-venecku
talks:
- title: SSL certificates minimum + live demo
  speakers:
  - Jiri Barton
  urls:
  - http://lanyrd.com/2013/praha-pyvo-june/schztg/
  coverage:
  - slides: https://docs.google.com/presentation/d/12Tl3JFpGuMQ4wv2vETqlXz2e4T1BbWCOLHTi3J8VBvM/edit
  - video: http://www.youtube.com/watch?v=4J67TCn_C3Y
  - link: https://www.cheapssls.com/
- title: Hacknuti webserveru
  speakers:
  - Jirka Vejrazka
  urls:
  - http://lanyrd.com/2013/praha-pyvo-june/schzth/
  coverage:
  - slides: http://www.slideshare.net/JirkaV/sql-injection-attackanalysispyvo
  - video: http://www.youtube.com/watch?v=DhpnVGpRA-w
- title: Velke chyby na velkych portalech
  speakers:
  - Miloslav Pojman
  urls:
  - http://lanyrd.com/2013/praha-pyvo-june/sckctf/
  coverage:
  - slides: https://docs.google.com/presentation/d/1UOWGi3E5dePEa1s7mhrvUUIhvS4R2Qc4Tb9bgm_DlSg/
  - video: http://www.youtube.com/watch?v=uC1Pg3RhXNk
- title: lightning talks
  lightning: true
  speakers:
  - Jakub Vysoký
  - Adam Kliment
  - dosky
  - Honza Král
  - Jiri Barton
  - Ales Zoulek
  urls:
  - http://lanyrd.com/2013/praha-pyvo-june/sckpbd/
  coverage:
  - video: http://www.youtube.com/watch?v=up_nNaClJlc&list=PLv71wFBVCTqEwSyQ3M2NQ5sS3w0CaBsbx&index=4
  description: |
    honza kral - ella/django security notes

    dosky - ctete security notes

    ales zoulek - djangocon a jine koneference

    adam kliment - apiary.io blueprints

    jiri barton - nejacatejsi hesla

    jakub vysoky - zizalarium, aneb jak vybudovat zizalovnik
urls:
- http://lanyrd.com/2013/praha-pyvo-june/
